CREATE TABLE IF NOT EXISTS secrets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    version INT NOT NULL,
    ciphertext VARBINARY(4096) NOT NULL,
    nonce VARBINARY(255) NOT NULL,
    tag VARBINARY(255) NOT NULL,
    wrapped_dek VARBINARY(4096) NOT NULL,
    kek_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    secret_id BIGINT,
    action VARCHAR(50),
    actor VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
